import './global.css';

import { Metadata } from 'next';
import { Poppins, Red_Hat_Display } from 'next/font/google';

const mainFont = Poppins({
  preload: true,
  adjustFontFallback: true,
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
  variable: '--main-font',
});

const subFont = Red_Hat_Display({
  preload: true,
  adjustFontFallback: true,
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
  variable: '--sub-font',
});

export const metadata: Metadata = {
  title: 'Welcome to portfoblogio',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${mainFont.variable} ${subFont.variable}`}>
      <body className="antialiased">{children}</body>
    </html>
  );
}
